server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com # eureka实例的主机名
  client:
    register-with-eureka: false # 不把自己注册到eureka上
    # 表示自己就是注册中心，职责就是维护服务器实例，并不需要检索服务
    fetch-registry: false
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/
